### ISSUE TITLE
question about this fork

### ISSUE THREAD

**Issue by amayra** [dinkc64/LakeSnes#1]
does this fork have some of speed optimizations from [reverse engineered clone of Zelda 3 with LakeSnes ](https://github.com/snesrev/zelda3)

since official repo has been archived and there link in readme to your fork

**Comment by dinkc64** [comment]
Hi,
Sorry for the -very- late response, for some reason the issues here didn't tag me :(
No, their fork basically neutered the ppu, making it unusable with any game but Zelda 3

best regards,
- dink
